Error: File 'gui_main.ui' is not valid

while executing 'C:\Users\asligar\Anaconda3\envs\compare_traces\Lib\site-packages\PySide6\uic -g python gui_main.ui'
